
language:  cpp
compiler:
  - g++
before_install:
  - pip install --user cpp-coveralls
script:
  - g++ –coverage program8.6.cpp -o program8.6.out 
  - ./program8.6.out --enable-gcov 
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'








